In [11]:
import pygmid
print(pygmid.__version__)
from pygmid import Lookup as lk
import pandas as pd
import numpy as np

1.2.12

In [6]:
import os
os.listdir('/foss/designs/Chipathon2025/lookup_tables')

['lookup_examples.ipynb',
 'nfet_03v3.mat',
 'pfet_03v3.mat',
 'README.md',
 'techsweep_plots_from_mat.ipynb']

In [12]:
n = lk('/foss/designs/Chipathon2025/lookup_tables/nfet_03v3.mat')
p = lk('/foss/designs/Chipathon2025/lookup_tables/pfet_03v3.mat')

In [45]:
Ls = [0.28, 0.5, 1, 2, 5]
id =  1e-6
gm_id = np.array([5, 10, 15, 20])
gm = gm_id*id

In [46]:
dfs = {}

for l in Ls:
    jd = n.lookup('ID_W', GM_ID=gm_id, L=l)
    w = id/jd
    cgg_w = n.lookup('CGG_W', GM_ID=gm_id, L=l)
    cgg = w*cgg_w
    ft = gm/cgg/(2*np.pi)
    df = pd.DataFrame([gm_id, gm, jd, w, cgg, ft], ['gm_id', 'gm','jd', 'w', 'cgg', 'ft'])
    dfs[l] = df

In [47]:
dfs[0.28]

                  0             1             2             3
gm_id  5.000000e+00  1.000000e+01  1.500000e+01  2.000000e+01
gm     5.000000e-06  1.000000e-05  1.500000e-05  2.000000e-05
jd     2.539270e-05  6.847242e-06  2.097482e-06  4.903808e-07
w      3.938140e-02  1.460442e-01  4.767622e-01  2.039232e+00
cgg    4.628606e-17  1.603948e-16  4.880348e-16  1.916292e-15
ft     1.719253e+10  9.922699e+09  4.891709e+09  1.661072e+09

In [49]:
dfs[0.5]

                  0             1             2             3
gm_id  5.000000e+00  1.000000e+01  1.500000e+01  2.000000e+01
gm     5.000000e-06  1.000000e-05  1.500000e-05  2.000000e-05
jd     1.727587e-05  4.366505e-06  1.331991e-06  3.078075e-07
w      5.788421e-02  2.290161e-01  7.507556e-01  3.248783e+00
cgg    1.044733e-16  3.721183e-16  1.036537e-15  3.733738e-15
ft     7.617016e+09  4.276998e+09  2.303172e+09  8.525234e+08

In [50]:
dfs[1]

                  0             1             2             3
gm_id  5.000000e+00  1.000000e+01  1.500000e+01  2.000000e+01
gm     5.000000e-06  1.000000e-05  1.500000e-05  2.000000e-05
jd     9.349394e-06  2.214810e-06  6.859555e-07  1.693961e-07
w      1.069588e-01  4.515060e-01  1.457820e+00  5.903322e+00
cgg    3.503697e-16  1.335114e-15  3.659760e-15  1.211743e-14
ft     2.271243e+09  1.192070e+09  6.523171e+08  2.626876e+08

In [51]:
dfs[2]

                  0             1             2             3
gm_id  5.000000e+00  1.000000e+01  1.500000e+01  2.000000e+01
gm     5.000000e-06  1.000000e-05  1.500000e-05  2.000000e-05
jd     4.688812e-06  1.033154e-06  3.063451e-07  7.298846e-08
w      2.132736e-01  9.679101e-01  3.264292e+00  1.370080e+01
cgg    1.349678e-15  5.618951e-15  1.630837e-14  5.555706e-14
ft     5.896035e+08  2.832467e+08  1.463864e+08  5.729423e+07

In [52]:
dfs[5]

                  0             1             2             3
gm_id  5.000000e+00  1.000000e+01  1.500000e+01  2.000000e+01
gm     5.000000e-06  1.000000e-05  1.500000e-05  2.000000e-05
jd     3.252039e-08  6.041127e-08  3.452128e-08  1.113545e-08
w      3.074994e+01  1.655320e+01  2.896764e+01  8.980327e+01
cgg    4.773171e-13  2.368412e-13  3.556449e-13  8.861956e-13
ft     1.667182e+06  6.719902e+06  6.712663e+06  3.591869e+06

In [53]:
dfs2 = {}

for l in Ls:
    jd = p.lookup('ID_W', GM_ID=gm_id, L=l)
    w = id/jd
    cgg_w = p.lookup('CGG_W', GM_ID=gm_id, L=l)
    cgg = w*cgg_w
    ft = gm/cgg/(2*np.pi)
    df = pd.DataFrame([gm_id, gm, jd, w, cgg, ft], ['gm_id', 'gm','jd', 'w', 'cgg', 'ft'])
    dfs2[l] = df

In [54]:
dfs2[0.28]

                  0             1             2             3
gm_id  5.000000e+00  1.000000e+01  1.500000e+01  2.000000e+01
gm     5.000000e-06  1.000000e-05  1.500000e-05  2.000000e-05
jd     9.824398e-06  2.585008e-06  8.122337e-07  1.658700e-07
w      1.017874e-01  3.868460e-01  1.231173e+00  6.028819e+00
cgg    1.269196e-16  4.698830e-16  1.446303e-15  6.649329e-15
ft     6.269910e+09  3.387119e+09  1.650638e+09  4.787098e+08

In [55]:
dfs2[1]

                  0             1             2             3
gm_id  5.000000e+00  1.000000e+01  1.500000e+01  2.000000e+01
gm     5.000000e-06  1.000000e-05  1.500000e-05  2.000000e-05
jd     2.217754e-06  5.218774e-07  1.584717e-07  3.285948e-08
w      4.509066e-01  1.916159e+00  6.310277e+00  3.043262e+01
cgg    1.609718e-15  6.650308e-15  2.111932e-14  9.498218e-14
ft     4.943566e+08  2.393197e+08  1.130398e+08  3.351259e+07

In [56]:
dfs2[2]

                  0             1             2             3
gm_id  5.000000e+00  1.000000e+01  1.500000e+01  2.000000e+01
gm     5.000000e-06  1.000000e-05  1.500000e-05  2.000000e-05
jd     1.017715e-06  2.357029e-07  7.143684e-08  1.503878e-08
w      9.825933e-01  4.242630e+00  1.399838e+01  6.649475e+01
cgg    6.629341e-15  2.742236e-14  8.496060e-14  3.587017e-13
ft     1.200383e+08  5.803839e+07  2.809919e+07  8.873945e+06

In [57]:
dfs2[5]

                  0             1             2             3
gm_id  5.000000e+00  1.000000e+01  1.500000e+01  2.000000e+01
gm     5.000000e-06  1.000000e-05  1.500000e-05  2.000000e-05
jd    -4.657746e-08 -5.563028e-09 -1.654140e-10  2.160215e-10
w     -2.146961e+01 -1.797582e+02 -6.045439e+03  4.629169e+03
cgg   -3.474574e-13 -2.723257e-12 -8.245538e-11  5.294225e-11
ft    -2.290280e+06 -5.844286e+05 -2.895292e+04  6.012398e+04